### ISSUE TITLE
Relationships can have "_" as argument?

### ISSUE THREAD

**Issue by davidzhao800** [CS3201-2/SPA#27]
need help.
Notes: Calls(_,_) is allowed but Follows(_,_)? Next(_,_)?

**Comment by davidzhao800** [comment]
From my point of view, only
Modifies(stmt, _) Uses( stmt,_ ) Call(_)(_,_) and Affects(_)(_,_)

**Comment by comilao** [comment]
Second of Modifies, and Uses, since it can only be variable type.
Both for Calls, since they can only be procedure.
Both  for Affects, since they can only be assignment.

If in general, Follows, Parent and Next have stmt as their argument, then they can also use _. Maybe we need to check with tutor.

**Comment by yeokangwei** [comment]
Modifies and Uses second argument can be underscore
Calls Affects can be both underscore
Follows, Parent -> Between statements 
Eg of valid queries: Select w such that Follows (_, _); Select s such that Parent(s, _);

**Comment by davidzhao800** [comment]
done by [3a06c10]
