### ISSUE TITLE
Bug in Validator

### ISSUE THREAD

**Issue by davidzhao800** [CS3201-2/SPA#99]
7 - Next_Parent_
while w; call calls;
Select w such that Next_(calls, w) and Parent_(w, 9)
8
5000

this one shows wrong query declaration

**Comment by ManikaAgarwal** [comment]
calls is a relationship. Can a relationship be a variable name?

**Comment by davidzhao800** [comment]
can, for example: call.procName = p.procName

**Comment by ManikaAgarwal** [comment]
So is  

procedure parent; 
Select BOOLEAN with parent.procName = "Sun"

a valid query?

**Comment by davidzhao800** [comment]
you misunderstand call and Calls

**Comment by davidzhao800** [comment]
if, while, call, assign

**Comment by davidzhao800** [comment]
Calls, Modifies, Uses are relationship

**Comment by davidzhao800** [comment]
maybe the declaration name is not properly, sth like this
call c;

**Comment by ManikaAgarwal** [comment]
Haha I didn't misunderstand. I was confused as to whether "calls" is a valid variable name since right now, I don't allow relationship names such as follows, parent, calls etc to be variable names. So is the original query valid or not? If it is, I'll change the validator to accept relationship names as variable names.

**Comment by davidzhao800** [comment]
oh, sorry!!!

**Comment by davidzhao800** [comment]
close this issue, my fault
